//
//  Item.swift
//  SwiftDemo
//
//  Created by Parth Gohel on 22/06/22.
//  Copyright © 2022 Parth Gohel. All rights reserved.
//

import UIKit

struct Item {
    let id: UUID
    let name: String
    let image: UIImage
    let color: UIColor
    var isSelected: Bool
}

extension Item {
    static var mockItems: [Self] {
        return [
            Item(id: UUID(),
                 name: "None",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Glazed",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Powdered Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate with Sprinkles",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Maple",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Regular",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Blueberry",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "None",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Glazed",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Powdered Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate with Sprinkles",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Maple",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Regular",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Blueberry",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "None",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Glazed",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Powdered Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate with Sprinkles",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Maple",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Regular",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Blueberry",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "None",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Glazed",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Powdered Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate with Sprinkles",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Maple",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Regular",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Blueberry",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
        ]
    }
}

//        arrData = ["None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple", "Regular", "Chocolate", "Blueberry", "Devil's Food", "None", "Glazed", "Sugar", "Powdered Sugar", "Chocolate with Sprinkles", "Chocolate", "Maple"]
