//
//  Item.swift
//  SwiftDemo
//
//  Created by Parth Gohel on 22/06/22.
//  Copyright © 2022 Parth Gohel. All rights reserved.
//

import UIKit

struct DataCollection {
    let id: Int
    let title:String
    var item: [Item]
    
    mutating func add(newItem: Item) {
        item.append(newItem)
    }
    mutating func remove(newItem: Item) {
        item = item.filter({$0.id != newItem.id})
    }
}
struct Item {
    let id: UUID
    let name: String
    let image: UIImage
    let color: UIColor
    var isSelected: Bool
}

extension DataCollection {
    static var sectionItems: [Self] {
        return [
            DataCollection(id: 0, title: "Items name", item: [
                Item(id: UUID(),
                     name: "None",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Glazed",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Sugar",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Powdered Sugar",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolate with Sprinkles",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolate",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Maple",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Regular",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolate",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Blueberry",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
            ]),
            DataCollection(id: 1, title: "Items name", item: [
                Item(id: UUID(),
                     name: "Nothing",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Glazeded",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Sugars",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Powdered Sugars",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolates with Sprinkles",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolates",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Maples",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Regulars",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolates",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Blueberrys",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
            ]),
            DataCollection(id: 2, title: "Items name", item: [
                Item(id: UUID(),
                     name: "Nothing",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Glazeded",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Sugars",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Powdered Sugars",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolates with Sprinkles",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolates",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Maples",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Regulars",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Chocolates",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
                Item(id: UUID(),
                     name: "Blueberrys",
                     image: ItemResource.chocolate.image,
                     color: .orange,
                     isSelected: false),
            ])
        ]
    }
}


extension Item {
    static var mockItems: [Self] {
        return [
            Item(id: UUID(),
                 name: "None",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Glazed",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Powdered Sugar",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate with Sprinkles",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Maple",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Regular",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Chocolate",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false),
            Item(id: UUID(),
                 name: "Blueberry",
                 image: ItemResource.chocolate.image,
                 color: .orange,
                 isSelected: false)
        ]
    }
}
